# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db1231387b5f0d77606e74da2ad19a6c7c7b2d3c6a27be80283d393805eccc1ce4bcc0df7ace8ddae1c442937e4a3d5f38e1b9c655bb5e3f35645948c74ff5df

test:
  secret_key_base: 039e87f277ec36729f5f33b70b7a556cb2f262278d350ec91dbcf67e39c0e0c9d20220ee493cb57b7b2c7ffdd1f6f15248226d59930d2813aba9a0674a3cbdd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
